spring.application.name=ecom.proj
server.port=8081
# ======================
# DATABASE CONNECTION
# ======================

spring.datasource.url=jdbc:mysql://localhost:3306/ecommercedb
spring.datasource.username=root
spring.datasource.password=root@123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ======================
# JPA SETTINGS
# ======================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

paypal.client.id=AU01ajw8TYO7394krDdtn58dxluNTWGhIKKsCjk9iISpu6D57NDksQKpQwuAjrZ0uw_5G1SdCIN9cbtr
paypal.client.secret=ECSf0x9ZcyCLshRgvM6G7kOzfrmQdanpiG5m_C1cy5GnO0RXruS6g6fu9wp9b7MUWa11holpOLraGo8z
paypal.mode=sandbox